//! English layout: phoneme inventory, brief tables, suffix system, spelled-number forms.
//!
//! Hand-tuned (`chords`, `ordered_briefs`, `suffixes`, `number_forms`) and autogenerated (`briefs`) submodules describing how rhe maps the 9-bit chord space to English phonemes and words. Selected at compile time via the `lang-en` Cargo feature; see `src/layout/mod.rs` for the dispatch.

pub mod briefs;
pub mod chords;
pub mod number_forms;
pub mod ordered_briefs;
pub mod suffixes;
