//! Compile-time user-adjustable mappings.
//!
//! Each submodule is a `.rs` file that doubles as editable text — some
//! hand-tuned (layout, suffixes, number positions), some autogenerated
//! by the gen_briefs binary (briefs_data, ordered_briefs_data). Edit
//! the file (or rerun the generator) and recompile to change the
//! binding; there's no runtime config layer, the compiler sees the
//! single source of truth and folds the dispatch tables straight into
//! the resulting binary.

pub mod briefs;
pub mod briefs_data;
pub mod chord_map;
pub mod layout;
pub mod number_data;
pub mod number_forms;
pub mod ordered_briefs_data;
pub mod suffixes_data;
