//! Compile-time user-adjustable mappings.
//!
//! Each submodule is a `.rs` file that doubles as editable text — some hand-tuned (layout, suffixes, number positions), some autogenerated by the gen_briefs binary (briefs, ordered_briefs). Edit the file (or rerun the generator) and recompile to change the binding; there's no runtime config layer, the compiler sees the single source of truth and folds the dispatch tables straight into the resulting binary.

pub mod briefs;
pub mod chords;
pub mod keyboard;
pub mod numbers;
pub mod number_forms;
pub mod ordered_briefs;
pub mod suffixes;
